// <auto-generated />
using System;
using Dev.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dev.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240514093821_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dev.Common.Models.Depense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Montant")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Depenses");
                });

            modelBuilder.Entity("Dev.Common.Models.SuiviDepense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepenseId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepenseId");

                    b.ToTable("SuiviDepenses");
                });

            modelBuilder.Entity("Dev.Common.Models.SuiviDepense", b =>
                {
                    b.HasOne("Dev.Common.Models.Depense", "Depense")
                        .WithMany("SuiviDepenses")
                        .HasForeignKey("DepenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depense");
                });

            modelBuilder.Entity("Dev.Common.Models.Depense", b =>
                {
                    b.Navigation("SuiviDepenses");
                });
#pragma warning restore 612, 618
        }
    }
}
